### ISSUE TITLE
Segmentation Fault when running Homebridge

### ISSUE THREAD

**Issue by leoneleone** [pdlove/homebidge-sensibo#2]
Hi,

Thanks so much for writing this plugin. I've been waiting for this for quite some time. If my coding skills were adequate enough I would have tried making a plugin myself.

I've managed to install your plugin, but run into a Segmentation Fault error when running Homebridge. 
"[Sensibo] Initializing platform accessory 'Bedroom AC'...
[Sensibo] Initializing platform accessory 'LivingRoom AC'...
[Sensibo] Initializing platform accessory 'Guest Room AC'...
Segmentation fault"

The segmentation fault does not happen if I remove Sensibo from my config.json file.
perhaps its an incompatibility with the latest version of homebridge, or the nodejs version?

Hope you can help.

**Comment by pdlove** [comment]
I didn't realize I had uploaded this yet. I've got a fix for this that will be uploaded this weekend.

**Comment by pdlove** [comment]
Try it now. I also deployed an npm package.
I'm getting some failures in the API calls, but the report from @payote is that he gets errors on the same commands from the app itself, so I think it's a setup issue with the units I've used for testing.
I do have http responses from the API when updating settings going to the console, so it will be a little noisy. I'll suppress those to debug mode once I get confirmation that this is working for everyone.

**Comment by payote** [comment]
@leoneleone - was it a segmentation fault 11? I ran into that error last night, but resolved it after deleting /node-modules, reinstalling node-js/npm, homebridge and my homebridge plugins. After that I was able to use the unreleased plugin and all pods were discovered and reported their states. Not sure which link in the chain was broken, but that fixed it for me.

OS X 10.11.3
node 5.5.0

**Comment by leoneleone** [comment]
@payote - I'm running homebridge on a Pi2
I was getting an output that simply said "Segmentation fault". Since then I've had problems with running homebridge. After removing my homebridge from the my iOS HomeKit Configuration and trying to re-add it, iOS wasn't able to pair with my homebridge device/accessory although it could clearly find it.
I haven't had a chance to fix this yet, but I believe your solution will resolve all the problems that have popped up for me, including the 'not being able to pair homebridge'.
Must be something to do with the amount of times I change my config.json file while testing the first version of the plugin.

@pdlove - Will get a chance to try again tomorrow hopefully. I'll let you know what happens :)

**Comment by leoneleone** [comment]
@pdlove - Ok so I managed to setup everything again last night and homebridge ran with the homebridge-sensibo plugin installed. My ACs were detected and relevant parameters/states were visible in Eve.app on my iPhone (I also use HMCatalog.app). Unfortunately, only the FAN settings seemed to work. AC mode changes don't reach the pods for some reason. I also had one of my three pods disconnect from my Sensibohub - it just doesn't work anymore. I've removed that pod from the sensible account and will be re-addinig it again shortly.

I was going to look into the homebridge debug output today and run some tests, but for some reason Homebridge and all it's bridged accessories disappeared from my HomeKit Configuration. Very strange.

Decided to reset the HomeKit Configuration and start with an all new setup.

Could there be something in the homebridge-sensibo plugin that's causing the API faults? Both homebridge and the Sensibo.app seem to be effected by using the plugin.

I'll keep you updated

**Comment by pdlove** [comment]
It shouldn't be possible for the plugin to cause problems with the native Sensibo app. That being said, working with the API has actually made me decide against investing in a Sensibo device for myself. Honestly, I think they need to do more work on the API interface to make it solid.

I will add more debugging output tomorrow to get more information about what the plugin is actually doing.

**Comment by frolov32** [comment]
Works for me "out of the box". Correctly displays temperature and humidity from both my pod's. I still do not understand how to switch on the last selected mode. My air conditioner turns on only if I change the target temperature. But it works correctly. Thank you for the work. It would be great if you continue debugging the plugin.
![img_1577](https://cloud.githubusercontent.com/assets/15147503/12701037/3e58e720-c80c-11e5-982e-6d015920055d.jpg)

**Comment by payote** [comment]
@frolov32 Are you able to with between temperature display units? It seems that Sensibo prefers to stay in Celsius - when I switch to Fahrenheit it defaults back to C every time.

**Comment by leoneleone** [comment]
@frolov32 Are you able to switch modes (Target Heating Cooling State) from Heat to Cool? 
Do all the Siri voice commands work for you?

**Comment by leoneleone** [comment]
@pdlove - keep getting some Syntax Errors when running commands:

>   EventedHTTPServer [192.168.1.96] Sending HTTP event '25.16' with data: {"characteristics":[{"aid":25,"iid":16,"value":25}]} +9s
> response in http: <h1>Server Error (500)</h1>
> SyntaxError: Unexpected token <
>     at Object.parse (native)
>     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-sensibo/lib/sensiboapi.js:32:19)
>     at emitNone (events.js:72:20)
>     at IncomingMessage.emit (events.js:166:7)
>     at endReadableNT (_stream_readable.js:903:12)
>     at doNTCallback2 (node.js:439:9)
>     at process._tickCallback (node.js:353:17)
> raw message <h1>Server Error (500)</h1>
>

**Comment by leoneleone** [comment]
@pdlove -

 is there any way of adding (Characteristic.RotationSpeed)  to "Service.Thermostat" -- rather than "Service.Fan"?  and then creating a new characteristic (Characteristic.FanOn) that becomes part of "Service.Thermostat" in the same way...?

Or maybe integrating the Sensibo "Fan mode" so that it is part of TargetHeatingCoolingState=(AUTO) rather than having the Fan setting show up as an individual power switch?

I believe the limitations of integrating AC units with HomeKit has more to do with the lack of a dedicated AirConditioner Service (Service.AirCon) within the HomeKit API. 

Haier have a HomeKit Compatible AC on the market (only sold in the Far-East currently). I wonder how they have managed that.

Other than Sensibo, Tado have announced official HomeKit integration sometime in April 2016. I believe they must be struggling with the same issues you are facing with the homebridge-sensibo app.

Thanks for all the work you've put into the plugin so far :)

**Comment by pdlove** [comment]
I'll continue to work on this as best as I can. What app are you using that the multiple services are causing an issue? 
I'll add the fan speed characteristic to the Thermostate service but I don't think I can create a new characteristic. I have a HomeKit enabled thermostat and it disables manual fan control altogether when HomeKit is enabled.

**Comment by leoneleone** [comment]
The other possible solution is to have each Sensibo Pod show up as 2 separate HomeKit Accessories/devices (two independent services):
1. Sensibo thermostat device - with all its relevant controls: On, temperature, heatingcoolingstate, etc
2. Sensibo fan device - with separate controls for: On, Fan rotation speed.

For creating new Characteristic please look at the homebridge-nest implementation of 'Away' status. They've managed to create and add a new characteristic toggle for the nest away api. Maybe that can help?
